"""validation through dataclasses

Revision ID: 0aa972af06d3
Revises: 9bd59cf91eee
Create Date: 2023-06-28 17:49:54.274910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0aa972af06d3"
down_revision = "9bd59cf91eee"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "username", sa.VARCHAR(length=80), autoincrement=False, nullable=False
        ),
        sa.Column("email", sa.VARCHAR(length=120), autoincrement=False, nullable=False),
        sa.Column("add", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="user_pkey"),
        sa.UniqueConstraint("email", name="user_email_key"),
        sa.UniqueConstraint("username", name="user_username_key"),
    )
    # ### end Alembic commands ###
