"""datatype changed of authur id

Revision ID: d7d48b142b76
Revises: 51bf32896c63
Create Date: 2023-06-28 18:15:33.733786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d7d48b142b76"
down_revision = "51bf32896c63"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("practice_pokemon")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "practice_pokemon",
        sa.Column("name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("color", sa.TEXT(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("name", name="practice_pokemon_pkey"),
    )
    # ### end Alembic commands ###
